stages:
  - name: deploy
    if: branch = master

language: php

php:
  - 7.0

install:
  - composer install

script: skip

deploy:
  #- "find vendor -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/{} \\;"
  - "find api -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/{} \\;"

env:
  global:
    - secure: aCasnrTpxngAvw0YJL8TthfCR+sWW00hVgGHGls+QzXEnJxsIWiH9i+mHWp6vYNbJK7Csr1TD9GFbE/L51EGB9GmExR4Wf4JK3TiC8i6S/hIki3JCpCZaiDKArknFvF5MtWtJUOGpB+IixxX24QQKrK6YQ54RhoEazJUItlk0t+3P80EcMDkn+lLaXQwoeSJI36Z+jsWTEL5pZ8OMS3+sas855oKn3YuClvSQQnclMZMSoQcpEd1lP/xMcXjh8ryh3kymNJyg5Qts+WJdarazc2clRYCczESFP/6SX0kQOWI8rsK1NxtkpqvtP/KN7PofT9IKoPnAZsqzOrgvjEXnw0vzNYCxT/HD4s4NmaWOClslev9OCKxP0fdXXi29eIpLxNr5U+yeaxuGXlizsP1BcQRAhE3MBJ4E45iFZJOJi0+pgXjsUItgLh6iaukSBjA/+G8ACGe15b06NwBuZdV2RJnDv8aHZ+kgQlAvZao67PbS59AyvDr8JPsVSQ3O6ZneSWJh5y8flH70H6anbRnuUz+HRP9ANgHWTNw7pMBy3RjGCETgE/UEd++LbANAzEKB9i60ieRLeIekOeS4Oh2XGe3kgYgbMiRPjRaenJTKshvqnDCgjghfpVFjHkS5zMmDQYQK85ZUkezkMMjrbr22alaJJgK+17xaiH05eJKMrs=
    - secure: l93yXbbllgS9hl4Mhsu1KA0UA/NCHYG1yFq81P2FCqGMLUw1c6sFPwM54akCKirN2RS3Pw0d8u84ODG1ixw98XZat6RkKORz6ZpmyNvOA5Lx1ibCl1wWtDgltwrtCqbrelf1hg6bLJ8Gf10FDWneV2S4bz43CKVgs2Xwt/HYmvvdlvBTzl1L/YVp/13qO31PtdrbbFQex7a2eoHJYgjiJiJNaWaPMRK8f7go5wBF3hXHdWvZXTeoqOa12y9w9M/cZPee1tuUtdSS1OpmwjaMK5xsQJDSi5haXqEIHGF9EjkYy/TQw11MW388V4MViT7dlLmoTBPW4oTMvYGYJYD/ugR2n5wjN7ZxuDHLbSwpXAd3zF5Mhf4mKX8rFG2oYNOIbAIzyk60Zx85CAa9t0u6f7BLsIB93tMw8pGYJLerfIYSTChn1tXHTIAwOQHkdNOkwkv/kUJY0Y4ZK3hVfl64gRH8dgQ755ovocK3vuzFLhdv7GdaWQGPUljPqjDVgsxHph3IOn5xhlTJPjZitskWzgEKX4Z1DiLTwJzX7/4uBf4RD6YowAd2yAQeUu4hv8oAnEFM+eSCP5/2676uI5PTevr0QX0hDX0RWkn2YvHJbhnq5b1wffEQYYj6pOV01BjCpjapfdujLZM6zcqtypLq4fn5QIAXpiVNqz/Nom8Mz8A=

